### ISSUE TITLE
Darkening when specific domains only

### ISSUE THREAD

**Issue by ALTanir** [notalex/super-dark-mode#5]
I want _web page to darker only specific domain, not for all as default_. So it needs a list to dark color for the linked page- which is listed. And others all are non-darken. For example(the system will be-)
Huge number of domains can visit by users. Yes, users who wants it always switching on/off for any site with their white list. And but some request is nearly same-that is, which users never need to use this darker software. But only for (suppose-) facebook, instagram, twitter, gmail, example.com1 ,2, and 3 (this 7 domains). He/she needs the list up. So two mode/group for list: 1)white list-not to darken & 2) **Off mode-** to perform darkening(for listed up) when switched off. And here, can disable option also be set.
Then users can disable extension or delete list as needs. I am all right? Thank you

**Comment by notalex** [comment]
Hi. Unfortunately, I don't use this plugin anymore, because I found that it slowed down the browser. Also this doesn't work with latest firefox. You would be better off with a something more actively maintained. Thanks.
